version: '2.1'
services:
  scrapy:
    build:
      context: .
      dockerfile: Dockerfile-crawler
    links:
    - scrapoxy
    env_file:
    - crawler/scrapy.env
    - crawler/scrapy.secrets.env
    hostname: ip6-scrapy
    network_mode: bridge

  scrapoxy:
    image: fabienvauchelles/scrapoxy
    env_file:
    - crawler/scrapoxy.env
    - crawler/scrapoxy.secrets.env
    expose:
    - 8888
    - 8889
    hostname: ip6-scrapoxy
    network_mode: bridge
