FROM python:3.6

RUN apt-get update \
 && apt-get install -y gdal-bin \
 && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# requirements
COPY crawler/requirements.txt /usr/src/app/

RUN pip install --no-cache-dir -r requirements.txt

# code
COPY . /usr/src/app

RUN cd models && pip install -e .

WORKDIR /usr/src/app/crawler

ENTRYPOINT ["scrapy", "crawl"]

# build: docker build -t "ip6-crawler" .

# usage example: docker run --rm ip6-crawler homegate
